# Generated by Django 4.1.4 on 2023-03-13 22:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('mvt_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('detailtransport', models.CharField(default='', max_length=150)),
                ('created', models.CharField(default='', max_length=50)),
                ('modified', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Enceinte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=10)),
                ('nomEnceinte', models.CharField(max_length=100)),
                ('adresse', models.CharField(default='', max_length=150)),
                ('contact1', models.CharField(blank=True, default='', max_length=9, null=True)),
                ('contact2', models.CharField(blank=True, default='', max_length=9, null=True)),
                ('mvt_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('categorie', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='RESEAU.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEquip', models.CharField(max_length=50, unique=True)),
                ('mesenceintes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Nivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(default='FOSA', max_length=50)),
                ('codenivo', models.CharField(default='FS', max_length=2)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Reso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reseau', models.CharField(default='CENTRE', max_length=50)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='PUBLIC', max_length=50)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('code', models.CharField(default='', max_length=10)),
                ('nom', models.CharField(default='', max_length=150)),
                ('telephone', models.CharField(max_length=9, unique=True)),
                ('email', models.EmailField(default='', max_length=254)),
                ('dteEnrollement', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(choices=[('F', 'F'), ('M', 'M')], default='F', max_length=150)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='user/')),
                ('mvt_at', models.DateTimeField(auto_now_add=True)),
                ('suspendu', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modify_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(default='', max_length=25)),
                ('cautionAdminission', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('enceinte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='RESEAU.enceinte')),
            ],
        ),
        migrations.CreateModel(
            name='Referer',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('caregiven', models.CharField(default='', max_length=150)),
                ('transport', models.CharField(choices=[('AMBULANCE', 'AMBULANCE'), ('VEHICULE PERSONNEL', 'VEHICULE PERSONNEL'), ('TRANSPORT EN COMMUN', 'TRANSPORT EN COMMUN'), ('AUTRE MOYEN', 'AUTRE MOYEN')], default='AUTRE MOYEN', max_length=150)),
                ('dterefencement', models.DateField(default='')),
                ('mvt_at', models.DateTimeField(auto_now_add=True)),
                ('created', models.CharField(default='', max_length=50)),
                ('modified', models.CharField(default='', max_length=50)),
                ('demande', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='RESEAU.demande')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RESEAU.referer')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nompatient', models.CharField(max_length=250)),
                ('dtenaiss', models.DateField(blank=True, null=True)),
                ('lieunaiss', models.CharField(default='', max_length=100, null=True)),
                ('poids', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pathologie', models.CharField(max_length=250)),
                ('ethnie', models.CharField(default='', max_length=15)),
                ('religion', models.CharField(default='', max_length=15)),
                ('profession_tuteur', models.CharField(default='', max_length=25)),
                ('contact', models.CharField(default='', max_length=15)),
                ('sexe', models.CharField(choices=[('F', 'F'), ('M', 'M')], default='F', max_length=150)),
                ('created', models.CharField(default='', max_length=50)),
                ('modified', models.CharField(default='', max_length=50)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='unuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EncUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointfocal', models.BooleanField(default=False)),
                ('dte', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('enceinte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enceintes', to='RESEAU.enceinte')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='enceinte',
            name='niveau',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='RESEAU.nivo'),
        ),
        migrations.AddField(
            model_name='enceinte',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RESEAU.enceinte'),
        ),
        migrations.AddField(
            model_name='enceinte',
            name='reseau',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='RESEAU.reso'),
        ),
        migrations.AddField(
            model_name='enceinte',
            name='secteur',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='RESEAU.secteur'),
        ),
        migrations.AddField(
            model_name='demande',
            name='encuser',
            field=models.ForeignKey(default='', max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='encusers', to='RESEAU.encuser'),
        ),
        migrations.AddField(
            model_name='demande',
            name='patient',
            field=models.ForeignKey(default='', max_length=25, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='RESEAU.patient'),
        ),
        migrations.CreateModel(
            name='Appartenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pu', models.FloatField(default=0)),
                ('periodicite', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appartenirequipement', to='RESEAU.equipement')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appartenirservice', to='RESEAU.servico')),
            ],
        ),
    ]
