# Generated by Django 4.1.4 on 2023-01-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESEAU', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enceinte',
            name='adresse',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='enceinte',
            name='contact1',
            field=models.CharField(blank=True, default='', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='enceinte',
            name='contact2',
            field=models.CharField(blank=True, default='', max_length=9, null=True),
        ),
    ]
