# Generated by Django 4.1.4 on 2023-02-08 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RESEAU', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reso',
            old_name='nonreso',
            new_name='nomreso',
        ),
        migrations.RenameField(
            model_name='secteur',
            old_name='nomSecteur',
            new_name='nom',
        ),
    ]
