# Generated by Django 4.1.4 on 2023-01-07 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RESEAU', '0002_alter_enceinte_adresse_alter_enceinte_contact1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enceinte',
            name='nivo',
        ),
        migrations.AlterField(
            model_name='enceinte',
            name='reso',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='RESEAU.reso'),
        ),
    ]
