# Generated by Django 4.1.4 on 2023-01-07 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RESEAU', '0003_remove_enceinte_nivo_alter_enceinte_reso'),
    ]

    operations = [
        migrations.AddField(
            model_name='enceinte',
            name='nivo',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='RESEAU.nivo'),
        ),
    ]
