# Generated by Django 4.1.4 on 2023-02-17 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RESEAU', '0003_nivo_codenivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
    ]
