# Generated by Django 4.1.4 on 2023-02-18 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RESEAU', '0005_alter_enceinte_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enceinte',
            name='secteur',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='RESEAU.secteur'),
        ),
    ]
