# Generated by Django 4.1.4 on 2023-02-21 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RESEAU', '0006_alter_enceinte_secteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='caregiven',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='transport',
        ),
        migrations.AddField(
            model_name='referer',
            name='caregiven',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='referer',
            name='demande',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='RESEAU.demande'),
        ),
        migrations.AddField(
            model_name='referer',
            name='transport',
            field=models.CharField(choices=[('AMBULANCE', 'AMBULANCE'), ('VEHICULE PERSONNEL', 'VEHICULE PERSONNEL'), ('TRANSPORT EN COMMUN', 'TRANSPORT EN COMMUN'), ('AUTRE MOYEN', 'AUTRE MOYEN')], default='AUTRE MOYEN', max_length=150),
        ),
    ]
