# Generated by Django 4.1.4 on 2023-03-04 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RESEAU', '0007_remove_demande_caregiven_remove_demande_transport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referer',
            name='demande',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referer', to='RESEAU.demande'),
        ),
    ]
