# Generated by Django 4.1.4 on 2023-03-04 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RESEAU', '0008_alter_referer_demande'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Servico',
        ),
    ]
