# Generated by Django 4.1.4 on 2023-03-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESEAU', '0009_rename_service_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='nomService',
            field=models.CharField(default='', max_length=25),
        ),
    ]
