# Generated by Django 4.1.4 on 2023-03-05 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RESEAU', '0010_alter_servico_nomservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='enceinte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RESEAU.enceinte'),
        ),
    ]
