# Generated by Django 4.1.4 on 2023-03-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESEAU', '0011_alter_servico_enceinte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='cat',
            new_name='categorie',
        ),
        migrations.RenameField(
            model_name='enceinte',
            old_name='category',
            new_name='categorie',
        ),
        migrations.RenameField(
            model_name='enceinte',
            old_name='nivo',
            new_name='niveau',
        ),
        migrations.RenameField(
            model_name='enceinte',
            old_name='reso',
            new_name='reseau',
        ),
        migrations.RenameField(
            model_name='nivo',
            old_name='nivo',
            new_name='niveau',
        ),
        migrations.RenameField(
            model_name='reso',
            old_name='nomreso',
            new_name='reseau',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='nomService',
            new_name='service',
        ),
        migrations.AddField(
            model_name='patient',
            name='contact',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='patient',
            name='ethnie',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='patient',
            name='profession_tuteur',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='patient',
            name='religion',
            field=models.CharField(default='', max_length=15),
        ),
    ]
